
/**
 * ./js/audioDB.js
 * This module is responsible for handling the audio database, including loading and managing audio files in transcription section
 * 
 * - completely generated by Claude....
 * ------------------------------------
 */



/**
 * The database name and version 
 * TO add a new store, etc just increment the version number
 * and the browser will run onupgradeneeded again to update it
 */
const DB_NAME = 'auralis-audio-db';
const DB_VERSION = 1;
const STORE_NAME = 'audio'; // think of this like a table name

/**
 * Opens (or creates) the IndexedDB database.
 * Returns a Promise that resolves with the db connection.
 * This is called internally by the other functions - you never call it directly.
 */
function openDB() {
  return new Promise((resolve, reject) => {

    // indexedDB.open() either opens an existing DB or creates a new one
    const request = indexedDB.open(DB_NAME, DB_VERSION);

    // This only runs the very first time, or when DB_VERSION is bumped
    // It's where you define your "tables" (called object stores in IndexedDB)
    request.onupgradeneeded = (e) => {
      const db = e.target.result;
      // Create the audio store only if it doesn't exist yet
      if (!db.objectStoreNames.contains(STORE_NAME)) {
        db.createObjectStore(STORE_NAME);
        // No keyPath here - we'll provide our own key ('current') when writing
      }
    };

    request.onsuccess = (e) => resolve(e.target.result); // gives us the db object
    request.onerror = (e) => reject(e.target.error);
  });
}

/**
 * Saves an audio Blob (the raw file) into IndexedDB under the key 'current'.
 * Whatever was there before gets overwritten - we only ever store one audio file.
 * 
 * @param {Blob|File} blob - The audio file from audioInput.files[0]
 */
export async function saveAudioBlob(blob) {
  try {
    const db = await openDB();

    // Wrap in a Promise so we actually wait for the write to finish
    return new Promise((resolve, reject) => {
      const tx = db.transaction(STORE_NAME, 'readwrite');
      const store = tx.objectStore(STORE_NAME);
      const request = store.put(blob, 'current');

      request.onsuccess = () => {
        console.log('Audio blob saved to IndexedDB');
        resolve();
      };
      request.onerror = (e) => reject(e.target.error);
    });

  } catch (err) {
    console.warn('Failed to save audio to IndexedDB:', err);
  }
}

/**
 * Retrieves the saved audio Blob from IndexedDB.
 * Returns the Blob if it exists, or null if nothing was saved.
 */
export async function getAudioBlob() {
  try {
    const db = await openDB();

    return new Promise((resolve) => {
      const tx = db.transaction(STORE_NAME, 'readonly'); // 'readonly' - just reading, no writing
      const store = tx.objectStore(STORE_NAME);
      const request = store.get('current'); // get the value stored under the key 'current'

      request.onsuccess = (e) => {
        // e.target.result is the blob if found, or undefined if nothing was saved
        resolve(e.target.result || null);
      };
      request.onerror = () => resolve(null); // if anything goes wrong, return null gracefully
    });

  } catch (err) {
    console.warn('Failed to get audio from IndexedDB:', err);
    return null;
  }
}

/**
 * Deletes the saved audio from IndexedDB.
 * Call this when a new transcription starts so old audio doesn't linger.
 */
export async function clearAudioBlob() {
  try {
    const db = await openDB();
    return new Promise((resolve, reject) => {
      const tx = db.transaction(STORE_NAME, 'readwrite');
      const store = tx.objectStore(STORE_NAME);
      const request = store.delete('current');
      request.onsuccess = () => {
        console.log('Audio blob cleared from IndexedDB');
        resolve();
      };
      request.onerror = (e) => reject(e.target.error);
    });
  } catch (err) {
    console.warn('Failed to clear audio from IndexedDB:', err);
  }
}


